### ISSUE TITLE
How to bind express-gateway "host" to localhost and use an Nginx reverse proxy?

### ISSUE THREAD

**Issue by Nditah** [ExpressGateway/express-gateway#1004]
### Entering Issues

Express-Gateway is unable to bind to localhost or 127.0.0.1

The Reverse proxy works as expected for any other service apart from the gateway.

Accessing the gateway via the nginx returns a _Cannot GET /api/erp_ 

However, access the gateway locally on the machine works well as expected.

Binding   _host: localhost_ for the http in gateway.config.yml has no effect whatsoever.

How can I resolve this.

###  Gateway.config.yml

<pre>
http:
  port: 5000

admin:
  port: 9876
  host: localhost

apiEndpoints:
  api:
    host: localhost
    paths: '/ip'

  erp:
    host: localhost
    paths: ['/api/erp', '/api/erp/*']                    
                          
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'

  erpService:
    url: 'http://localhost:5010'                     
                          
      
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit

pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true

  erpPipeline:
    apiEndpoints:
      - erp
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: erpService
              changeOrigin: true
</pre>

### The Reverse proxy with Nginx

<pre>
server {
listen 82;

location / {
        proxy_pass http://localhost:5010;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        }
}

server {
listen 81;

location / {
        proxy_pass http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        }
}

</pre>

**Comment by ahmedmolawale** [comment]
I am also having this concern. @Nditah did you find a way around this?

**Comment by pdkproitf** [comment]
Me too. 
I got a problem with this. 

I found that the gateway always listens on the server IP address request but not the localhost request. 
I think that we need to make it support localhost requests.

**Comment by pdkproitf** [comment]
I found the solution, config the `hostname` to `0.0.0.0` 

```
"http": {
    "hostname": "0.0.0.0",
    "port": 10199
  },
```

**Comment by iamsajidjaved** [comment]
I have formatted _gateway.config.yml_ through[]( https://onlineyamltools.com/prettify-yaml) after my changes and it has started working.

NOW IT LOOK LIKE:

```
http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: /ip
  reqres:
    host: localhost
    paths: /api/users
serviceEndpoints:
  httpbin:
    url: https://httpbin.org
  reqresserv:
    url: https://reqres.in
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  reqrespipeline:
    apiEndpoints:
      - reqres
    policies:
      - proxy:
          - action:
              serviceEndpoint: reqresserv
              changeOrigin: true

```
