### ISSUE TITLE
How to correctly set-up CORS headers?

### ISSUE THREAD

**Issue by niculistana** [ExpressGateway/express-gateway#333]
Hello? I'm using [create react app](https://github.com/facebookincubator/create-react-app) along with [axios](https://github.com/mzabriskie/axios) to create a request to an express-gateway server. So far I am having trouble getting them to connect.

Here is my current pipeline:
```
pipelines:
  api:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: api
      - cors:
          - action:
              origin: 'http://localhost:3000/'
              methods: 'HEAD,PUT,PATCH,POST,DELETE'  
```

Here is the error I am getting:
`No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.`

Do I have to set-up the CORS headers for the service endpoint as well?

Any help would be appreciated!

**Comment by kevinswiber** [comment]
Hi, @niculistana.

Try placing the CORS policy above the proxy policy.  The order of policy instances is significant, as policy execution happens top-down.  The proxy should be the last in the list.

```yaml
pipelines:
  api:
    apiEndpoints:
      - api
    policies:
      - cors:
          - action:
              origin: 'http://localhost:3000/'
              methods: 'HEAD,PUT,PATCH,POST,DELETE'  
      - proxy:
          - action:
              serviceEndpoint: api
```
