### ISSUE TITLE
"Getting Started" Issue

### ISSUE THREAD

**Issue by kreig303** [ExpressGateway/express-gateway#365]
Hello,

Followed your "Getting Started" example on my Mac and when all was said and done had a confounding result returned when I attempted to use the auth key on the local endpoint:

```bash
$ curl -H "Authorization: apiKey XXX:XXX" http://localhost:8080/ip
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /ip</pre>
</body>
</html>
```

Switching off the `key-auth` and removing the Auth header from the command restored the auth-less behavior:

```bash
$ curl http://localhost:8080/ip
{
  "origin": "1.1.1.1"
}
```

My .yaml enclosed for your sake:

```yaml
http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  - name: default
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
```
