### ISSUE TITLE
Problem with response after set authorization key in header

### ISSUE THREAD

**Issue by arefm** [ExpressGateway/express-gateway#370]
Hey

I'm getting an Error 404 when trying to set my authorization key (key-auth) in the request header. I'm sure that there isn't any problem with my key because if I don't set it a Forbidden status will return.

**before setting any credentials:**
```bash
$ curl http://localhost:8080/ip
```
will return:
```json
{
  "origin": "5.116.28.133"
}
```

**after creating a key-auth credential:**
```bash
$ curl -H "Authorization: apiKey ${keyId}:${keySecret}" http://localhost:8080/ip
```
will return:
```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /ip</pre>
</body>
</html>
```

**and it's my gateway config:**
```yml
http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  - name: default
    apiEndpoints:
      - api
    policies:
    - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true

```

Does anyone know why this issue happens?

**Comment by kevinswiber** [comment]
Hey @arefm!

It looks like you have an indentation bug in the YAML config.  The `- key-auth:` line needs to move over a couple of spaces.  Here's the corrected config:

```yaml
http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  - name: default
    apiEndpoints:
      - api
    policies:
      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
```
