### ISSUE TITLE
express-session default MemoryStore causing memory leak [bug]

### ISSUE THREAD

**Issue by roccomuso** [ExpressGateway/express-gateway#479]
I saw you're using `express-session` to keep in-memory sessions with the built-in `MemoryStore`.

```yaml
session:
  secret: keyboard cat
  resave: false
  saveUninitialized: false
```

**The built-in MemoryStore is not production-ready**, expired sessions are not pruned, and as suggested on the express-session documentation, the usage will be discouraged in a near future.
Consider using an external leak-proof memory storage: [memorystore](https://github.com/roccomuso/memorystore) as pointed on their documentation.
