### ISSUE TITLE
Express-Gateway is crashing when a request can't be handled by any pipeline

### ISSUE THREAD

**Issue by XVincentX** [ExpressGateway/express-gateway#611]
Express Gateway is starting when is fed with the current configuration file

```yml
http:
  port: 8080
apiEndpoints:
  verticals:
    path: '/verticals'
  countries:
    path: '/countries'
  msm_standard_proxy:
    host: '*'
serviceEndpoints:
  msm_origin:
    url: 'https://httpbin.org/'
policies:
  - proxy
  - terminate
pipelines:
  common:
    apiEndpoints:
      - verticals
      - countries
    policies:
      - terminate:
          - action:
              statusCode: 200
              message: 'should stop here'
  verticals_pipeline:
    apiEndpoints:
      - verticals
    policies:
      - terminate:
          - action:
              statusCode: 500
              message: 'should NOT stop here'
```

and you try to hit an any route that is not in any pipeline.

[Test instance](https://glitch.com/edit/#!/express-gateway-test)

EG should probably return a 404 when no suitable no pipeline is matching the current request.
