### ISSUE TITLE
headerPrefix not getting applied after upgrading to v1.6.1

### ISSUE THREAD

**Issue by StickNitro** [ExpressGateway/express-gateway#619]
The headerPrefix doesn’t seem to be getting applied in 1.6.1, my config is:

```
      - headers: &common-headers
          - action:
              headerPrefix: eg-
              forwardHeaders:
                user-id: 'consumer.token.authenticatedUserId'
                last-login: 'consumer.token.createdAt’
```

I am getting the user-id header, however it is named user-id instead of eg-user-id as expected

See comments below from gist

Serhii Kuts @DrMegavolt 10:35
@StickNitro I’ve checked there was a fallback to headerPrefix https://github.com/ExpressGateway/express-gateway/blame/de501c6509a5256d867b5709f30bc20d6fdf8a08/lib/policies/headers/headers.js#L5
now it is removed. to make properties consistent
@XVincentX I’m curious is it possible to allow fields that are not in schema but still output a warning that field not from schema is in configuration ?

Vincenzo Chianese @XVincentX 10:39
I was exactly thinking the same.
There should be an option for sure.
@StickNitro Could you open an issue on the Gateway repository so I can track that and verify?
