### ISSUE TITLE
Add condition to match API Endpoint name

### ISSUE THREAD

**Issue by DrMegavolt** [ExpressGateway/express-gateway#622]
Scenario:
you point 2 API endpoints to the same pipeline API_A, API_B
And the reason you use single pipeline is because all policies are the same except of the proxy
you have 2 backend services. S_A for API_A and S_B for API_B

It is hard to write a condition on proxy to do routing S_A vs S_B 
you will have to copy the routing params from API Endpoint into condition 

Proposal

```
proxy:
  -
    condition:
       name: apiEndpointMatch
       apiEndpointName: API_A
    action:
       serviceEndpoint: S_A
  -
    condition:
       name: apiEndpointMatch
       apiEndpointName: API_B
    action:
       serviceEndpoint: S_B
```

cc @minotaurrr
