### ISSUE TITLE
Proxy policy — changeOrigin can be defined in two different places

### ISSUE THREAD

**Issue by XVincentX** [ExpressGateway/express-gateway#647]
The changeOrigin parameter can be defined in two different places. This is confusing.

```yaml
- proxy:
    - action:
        serviceEndpoint: backend
        changeOrigin: true
        proxyOptions:
          changeOrigin: false
```
