### ISSUE TITLE
EG should allow developer to define errors

### ISSUE THREAD

**Issue by djesani** [ExpressGateway/express-gateway#692]
At the moment, if a request is unauthorized or a service endpoint becomes unavailable, EG simply returns plain text responses, such as "UNAUTHORIZED" or "BAD GATEWAY".

EG should allow the developer to decide how the error is returned, for example a JSON response or a HTML response and gracefully fallback to the plain text errors if these are not defined by the developer.

**Comment by XVincentX** [comment]
The error handler is [here](https://github.com/ExpressGateway/express-gateway/blob/master/lib/policies/proxy/proxy.js#L57-L65)

Not to sure how we can implement a declarative yet flexible error handler.

**Comment by WebWorkDeveloper** [comment]
@XVincentX Hi, I had the same problem.

I need to always return the JSON. 

How can I send an error (JSON obj) if not one condition.pattern does not match?

```
....

pipelines:

  api:
    apiEndpoints:
      - base
    policies:
      - proxy:

          - condition:
              name: pathMatch
              pattern: '/serviecName/*'
            action:
              serviceEndpoint: someService

          - condition:
              name: pathMatch
              pattern: '/serviceName/*'
            action:
              serviceEndpoint: someService
```
