### ISSUE TITLE
CORS not working

### ISSUE THREAD

**Issue by TietjeDK** [ExpressGateway/express-gateway#696]
I'm facing an issue when trying to access one of my microservices behind the express-gateway on a localhost:

`Failed to load http://localhost:8080/data: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8888' is therefore not allowed access.`

My gateway.config.yml

```
http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  data-api:
    host: localhost
    methods: 'GET,POST,PUT' 
    paths: '/data' 
  product-api:
    host: localhost
    paths: '/products' 
serviceEndpoints:
  data-svc:
    url: 'http://localhost:8282'
  product-svc:
    url: 'http://localhost:6000'
policies:
  - cors
  - jwt
  - proxy
  - rate-limit
pipelines:
  data:
    apiEndpoints:
      - data-api
    policies:
      - cors:
          - action:
              origin: "*"
              methods: 'HEAD,PUT,PATCH,POST,DELETE'
              allowedHeaders: "Origin, X-Requested-With, Content-Type, Accept"
              preflightContinue: true
      - rate-limit:
          - action:                         # allow
              max: 10                       # max 10 request
              windowMs: 120000              # per 120 seconds
      - jwt:
          - action:
              secretOrPublicKeyFile: ./key/pubKey.pem
              checkCredentialExistence: false    

  products:
    apiEndpoints:
      - product-api
    policies:
      - proxy:
          - action:
              serviceEndpoint: product-svc 
              changeOrigin: true
```

Any suggestions?

**Comment by NomadXD** [comment]
@TietjeDK I am facing the same issue but couldn't get it resolved.

```
user:
    apiEndpoints:
      - user
    policies:
      - cors:
        - action:
            origin: '*'
            credentials: true
            methods: ['GET','POST','PUT','DELETE']
            allowedHeaders: ['Content-type','Authorization','Origin','Access-Control-Allow-Origin','Origin', 'Accept', 'X-Requested-With', 'Content-Type', 'Access-Control-Request-Method', 'Access-Control-Request-Headers','Authorization', 'Access-Control-Allow-Origin','X-TEST']
            exposedHeaders : ['Content-type','Authorization','Origin','Access-Control-Allow-Origin','Origin', 'Accept', 'X-Requested-With', 'Content-Type', 'Access-Control-Request-Method', 'Access-Control-Request-Headers','Authorization', 'Access-Control-Allow-Origin','X-TEST']
            preflightContinue: true
      - jwt:
        - action:
            secretOrPublicKey: 'secret'
            checkCredentialExistence: false
      - request-transformer:
        - action:
            body:
              add:
                user: req.user
      - proxy:
        - action:
            serviceEndpoint: noAuthService
```

When I try the above configuration, the same error occurs like yours.

```
Access to XMLHttpRequest at 'http://localhost:8080/api/user/31a19f8a-c76d-4051-a944-dad1b676c550' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
```

@TietjeDK @XVincentX  Any ideas to fix it  ? Am I missing something ? Thanks
