### ISSUE TITLE
apiEndpoints 'methods' option is undocumented

### ISSUE THREAD

**Issue by Tiberriver256** [ExpressGateway/express-gateway#722]
### Entering Issues
```methods``` option missing from apiEndpoint documentation.

https://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints/#description
![image](https://user-images.githubusercontent.com/6989492/40009507-3b566a34-5770-11e8-90ed-286314b1c3b9.png)

It would also be nice to have an additional example added such as

```yaml
apiEndpoints:
  help:                 # name, used as reference in pipeline
    host: '*'           # required, '*' will not check for host name
    paths: /help        # optional, by default will serve all requests - same as *

  api:                  # name, used as reference in pipeline
    host: '*.com'       # wildcard pattern support
    paths:
      - '/v1/*'         # string or array of strings
      - '/v2/*'

  example:              # name, used as reference in pipeline
    host: 'example.com'
    paths: /v2/*        # string or array of strings

  example2:              # name, used as reference in pipeline
    -  host: 'example2.com'
       paths: /v2/*        # string or array of strings
       methods: ["GET", "OPTIONS"]
       scopes: ["example2:read"]

    -  host: 'example2.com'
       paths: /v2/*        # string or array of strings
       methods: ["PUT", "POST", "PATCH", "DELETE"]
       scopes: ["example2:write"]
```
