### ISSUE TITLE
apiEndpoints json schema: The methods object should be an array of strings, not an array of arrays

### ISSUE THREAD

**Issue by Tiberriver256** [ExpressGateway/express-gateway#723]
Expected is to be either an array of strings or a string, not an array of array items.

```yaml
  example2:
    -  host: 'example2.com'
       paths: /v2/* 
       methods: ["GET", "OPTIONS"]
       scopes: ["example2:read"]
```

https://github.com/ExpressGateway/express-gateway/blob/758291c1a0c62a20a1219f8fc86b4bae560792d8/lib/config/schemas/gateway.config.json#L84-L92

I believe it should be:

```json
          "methods": {
            "type": [
              "string",
              "array"
            ],
            "items": {
              "type": "string"
            }
          }
```
