### ISSUE TITLE
[DOCS] data pipelines must be an array, but not all examples reflect this

### ISSUE THREAD

**Issue by danielo515** [ExpressGateway/express-gateway#736]
Hello, there are some examples, like the JWT one where policies is an object. Trying this approach (because the yml looks cleaner) produces the following error:

`error: [EG:config]  Error: data.pipelines['default'].policies should be array`

Not sure if I'm doing something wrong, or this is a documentation issue. Here is one example pipeline:

```yml
pipelines:
  apis:
    apiEndpoints:
      - api
    policies:
      - jwt:
        - action:
      - proxy:
        - action:
            serviceEndpoint: httpbin
            changeOrigin: true
  default:
    apiEndpoints:
      - auth
    policies:
      - proxy:
          - action:
              serviceEndpoint: authService 
              changeOrigin: true
```

That is correct. If I remove the `-` before each policy then the error appears.

Regards
