### ISSUE TITLE
Increase of response time

### ISSUE THREAD

**Issue by acarlstein** [ExpressGateway/express-gateway#767]
### Increase of response time

We got a microservice, lets call it A, which is reached via Express Gateway as the diagram shows below:

[Client] <=> [Express Gateway] <=> [MS A]

Everything is working fine. When we call the URL, we get a result back as expected.

However, when we added a rate limit of 10 calls per 60 seconds:
```
# Setting rate limit
- rate-limit:
     - action:
            # Limit to 10 per 60 seconds based on the req.user.sub
            max: 10
            windowMs: 60000
            rateLimitBy: "${req.user.id}"
            # Adds the following headers:
            #   X-RateLimit-Limit (# of requests allowed)
            #   X-RateLimit-Remaining (# of requests before hitting limit)
            headers: true
# End of setting rate limit
```
and we performed a load test with Postman (in order to test the rate limit), we found that the response time keep increasing:
```
"times": [ "349", "1399", "2399", "3338", "4305", "5384", "6307", "7367", "8285", "9365", "220" ],
```

Such results keep repeating each time we run the load test.

Just to be sure, we did the same load test directly to the microservice A and the response time is an average of <300ms; therefore, we are assuming that there is an issue with something else related with Express Gateway... maybe there is a configuration that we are missing perhaps?

Thanks for taking your time to go over this issue. 
The help is appreciated.

If I find a solution, I will make sure to added here and let you know.
