### ISSUE TITLE
stripPath not working

### ISSUE THREAD

**Issue by johnnywiller** [ExpressGateway/express-gateway#794]
Hi, I'm trying to use `stripPath` to remove path from `apiEndpoints`. All others path options behave as expected (`prependPath` and `ignorePath`). 

I'm doing an gateway to RestHeart. When I enter the URL:

`http://localhost:8081/api/mongo_collection` which points to gateway, I expect redirecting to RestHeart without `/api/` path, only the `mongo_collection`, but RH log keeps saying it's received:

`GET http://localhost:8080/api/mongo_collection from /192.168.0.1:45782`

Below is my `gateway.config.yml`

```
http:
  port: 8081
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  restheart:
    host: '*'
    path: '/api/*'
serviceEndpoints:
  restheart:
    url: 'http://localhost:8080/'
pipelines:
  default:
    apiEndpoints:
      - restheart
    policies:
      - proxy:
          - action:
              serviceEndpoint: restheart
              changeOrigin: true
              #ignorePath: true  <--- works normal
              #prependPath: true  <--- works normal
              stripPath: true  <--- not working

```
