### ISSUE TITLE
Apply scope based on URL match

### ISSUE THREAD

**Issue by johnnywiller** [ExpressGateway/express-gateway#803]
It's awesome that I can apply certain scopes to different API endpoints and different authentication policies.

**But I'm not sure if I can apply scopes based on URL matching**, just to be clear I trying to implement some kind of role access. If the URL begins with `/api/control1` only users with `control1` access are allowed, the same is for `/api/control2`. `control1` and `control2` are in fact the same API, and 1 and 2 represents two endpoints, there are many endpoints. So my config in gateway.config.yml is
```
apiEndpoints:
  api:
    host: '*'
    path: ['/api', '/api/*']
```
