### ISSUE TITLE
Can't parse '%' symbol

### ISSUE THREAD

**Issue by Kirillpryanikov** [ExpressGateway/express-gateway#808]
When try to use percent (%) symbol in url, has next error: 
```
URIError: Failed to decode param '/test/%'
    at decodeURIComponent (<anonymous>)
    at decode_param (/Users/smartit/WebstormProjects/Node/pro100_mir/stone-gateway/node_modules/express/lib/router/layer.js:171:12)
    at Layer.match (/Users/smartit/WebstormProjects/Node/pro100_mir/stone-gateway/node_modules/express/lib/router/layer.js:123:27)
    at matchLayer (/Users/smartit/WebstormProjects/Node/pro100_mir/stone-gateway/node_modules/express/lib/router/index.js:574:18)
    at next (/Users/smartit/WebstormProjects/Node/pro100_mir/stone-gateway/node_modules/express/lib/router/index.js:220:15)
    at expressInit (/Users/smartit/WebstormProjects/Node/pro100_mir/stone-gateway/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/Users/smartit/WebstormProjects/Node/pro100_mir/stone-gateway/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/smartit/WebstormProjects/Node/pro100_mir/stone-gateway/node_modules/express/lib/router/index.js:317:13)
    at /Users/smartit/WebstormProjects/Node/pro100_mir/stone-gateway/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/smartit/WebstormProjects/Node/pro100_mir/stone-gateway/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/smartit/WebstormProjects/Node/pro100_mir/stone-gateway/node_modules/express/lib/router/index.js:275:10)
    at query (/Users/smartit/WebstormProjects/Node/pro100_mir/stone-gateway/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/Users/smartit/WebstormProjects/Node/pro100_mir/stone-gateway/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/smartit/WebstormProjects/Node/pro100_mir/stone-gateway/node_modules/express/lib/router/index.js:317:13)
    at /Users/smartit/WebstormProjects/Node/pro100_mir/stone-gateway/node_modules/express/lib/router/index.js:284:7
```
Looks like the reason is they try to get url encoding symbol (like encoding from '%7B' to '{')

Is there possible way (like custom pipeline or custom middleware) to avoid error, or getting custom JSON response in this case?

**Comment by XVincentX** [comment]
@Kirillpryanikov I need you to provide more details or I can't debug the issue.

Can you post your `gateway.config.yml` file and show the cURL command you're using to trigger such error?

**Comment by Kirillpryanikov** [comment]
@XVincentX This is part my gateway.config.yml
```
http:
  port: 8300
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  apiAdmin:
    host: '*'
    paths: '/api/v1/admin/*'
  NotFound404:
    host: '*'
    paths: '*'
serviceEndpoints:
  adminApi:
    url: 'http://194.87.147.5:8100'
  NotFound404:
    url: 'http://194.87.147.5:8100/404'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - rewrite
pipelines:
  apiAdmin:
    apiEndpoints:
      - apiAdmin
    policies:
      - proxy:
        - action:
            serviceEndpoint: adminApi
            changeOrigin: true
  NotFound404:
    apiEndpoints:
      - NotFound404
    policies:
      - proxy:
        - action:
            serviceEndpoint: NotFound404
            changeOrigin: false
```
