### ISSUE TITLE
CORS policy configuration doesn't support Regular Expressions

### ISSUE THREAD

**Issue by albertlinga** [ExpressGateway/express-gateway#821]
CORS library support regular expression on Origin option.  So as js-yaml (yaml parser) by using tag !!js/regexp. However if you look at express-gateway/lib/policies/cors/index.js, the type only allows string, Boolean and array where array items are only strings. This in turn treats a regular expression value on the Origin as a literal string so the response header Access-Control-Allow-Origin value is the pattern itself.

For example: partial gateway config is

```
policies:
  cors:
    action: 
      origin: /\.domain\.com$/
      methods: 'GET, PUT, POST, DELETE, OPTIONS'
      allowedHeaders: ['Content-Type', 'Authorization']
      credentials: true
      optionsSuccessStatus: 200
```

The response header Access-Control-Allow-Origin value becomes the pattern itself '/\.domain\.com$' 

I can't do this
`origin: !!js/regexp /\.domain\.com$/`
It errors our saying the tag !!js/regexp is not recognized or not one of the acceptable types in the schema.    

In express-gateway/lib/config/config.js the line for js-yaml to load the config file is this 
`config = yamlOrJson.load(envReplace(fs.readFileSync(configPath, 'utf8'), process.env));`

According to the js-yaml documentation https://github.com/nodeca/js-yaml

load (string [ , options ])
Use with care with untrusted sources. The same as safeLoad() but uses DEFAULT_FULL_SCHEMA by default - adds some JavaScript-specific types: !!js/function, !!js/regexp and !!js/undefined.

FYI @XVincentX  thanks.
