### ISSUE TITLE
getting Cannot read property 'toString' of undefined when trying the jwt access token configuration

### ISSUE THREAD

**Issue by nirradi** [ExpressGateway/express-gateway#829]
I copy/pasted the example from the documentation

```
accessTokens:
  timeToExpiry: 7200000
  tokenType: jwt
  issuer: express-gateway
  audience: something
  subject: test
  secretOrPrivateKey: ssssst
```
EDIT: 

the error I'm actually seeing is this when I run npm start: 
```
/src/oauth/node_modules/express-gateway/lib/policies/jwt/jwt.js:11
  const extractor = extractors[params.jwtExtractor](params.jwtExtractorField);
                                                   ^

TypeError: extractors[params.jwtExtractor] is not a function
    at module.exports (/src/oauth/node_modules/express-gateway/lib/policies/jwt/jwt.js:11:52)
    at module.exports (/src/oauth/node_modules/express-gateway/lib/policies/oauth2/oauth2.js:123:12)
    at policy.policy.args (/src/oauth/node_modules/express-gateway/lib/policies/index.js:31:16)
    at pipelinePoliciesConfig.forEach.policyConfig (/src/oauth/node_modules/express-gateway/lib/gateway/pipelines.js:134:32)
    at Array.forEach (<anonymous>)
    at configurePipeline (/src/oauth/node_modules/express-gateway/lib/gateway/pipelines.js:112:26)
    at Object.module.exports.bootstrap (/src/oauth/node_modules/express-gateway/lib/gateway/pipelines.js:19:20)
    at bootstrap (/src/oauth/node_modules/express-gateway/lib/gateway/index.js:92:26)
    at module.exports (/src/oauth/node_modules/express-gateway/lib/gateway/index.js:20:39)
    at Main.run (/src/oauth/node_modules/express-gateway/lib/index.js:24:43)
    at Object.<anonymous> (/src/oauth/server.js:6:4)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

**Comment by nirradi** [comment]
OK, there was a field missing in the configuration for the policy (jwtExtractor)

```
- oauth2:
          action:
            jwt:
              issuer: express-gateway
              audience: something
              subject: test
              secretOrPublicKey: ssssst
              checkCredentialExistence: false
              jwtExtractor: 'authBearer'
```
and it wasn't clear from the documentation that this was required.
