### ISSUE TITLE
[Question] - Service Endpoint not provided - This proxy will permanently return 502

### ISSUE THREAD

**Issue by allanchua101** [ExpressGateway/express-gateway#844]
Hi All,

I'm getting a 'Service Endpoint not provided - This proxy will permanently return 502' warning message when I run my POC gateway using the yml file below. Any hints will help so much :)

```yml
http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints
  gatewayAPI:
    host: 'vue.gateway.sg'
    paths:
      - '/users'
      - '/products'
      - '/transactions'
serviceEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/serviceEndpoints
  usersService:
    url: 'http://localhost:8059'
  productsService:
    url: 'http://localhost:8060'
  transactionsService:
    url: 'http://localhost:8061'
policies:
  - expression
  - key-auth
  - proxy
  # - basic-auth
  # - cors
  # - expression
  # - key-auth
  # - log
  # - oauth2
  # - proxy
  # - rate-limit
pipelines:
  - name: users
    apiEndpoints:
      - gatewayAPI
    policies:
      - proxy:
        - action:
          serviceEndpoint: usersService
        #- action:
        #  serviceEndpoint: productsService
        #- action:
        #  serviceEndpoint: transactionsService
  # see: https://www.express-gateway.io/docs/configuration/gateway.config.yml/pipelines
```

**Comment by allanchua101** [comment]
Found the solution to this issue (It's a mistake on my side), serviceEndpoint is being analyzed as undefined because of the tabbing on the action item of the policy proxy which should have more indentation.

```yml
pipelines:
  - name: users
    apiEndpoints:
      - gatewayAPI
    policies:
      - proxy:
        - action:
            serviceEndpoint: usersService
```
