### ISSUE TITLE
Docker Swarm: cp: can't create '/var/lib/eg/models/users.json': File exists

### ISSUE THREAD

**Issue by JohnOllhorn** [ExpressGateway/express-gateway#865]
### Entering Issues

Hi folks,

I'm trying to deploy the official EG Docker image to Docker Swarm.
I have added the configuration files as Docker Config:

```yml
configs:
  eg_gateway_config:
    file: ./express-gateway/config/gateway.config.yml
  eg_system_config:
    file: ./express-gateway/config/system.config.yml
  eg_applications_models:
    file: ./express-gateway/config/models/applications.json
  eg_credentials_models:
    file: ./express-gateway/config/models/credentials.json
  eg_users_models:
    file: ./express-gateway/config/models/users.json
```

This is what the Docker Service looks like:

```yml
  truedev-gateway:
    image: express-gateway:latest
    networks: ['proxy','truedev']
    deploy:
      labels:
        traefik.enable:               "true"
        traefik.backend:              "api"
        traefik.weight:               10
        traefik.docker.network:       "proxy"
        traefik.port:                 7070
        traefik.frontend.rule:        "Host:api.DOMAIN"
        traefik.frontend.entryPoints: "https"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 20
        window: 380s
      placement:
        constraints: ['node.platform.os == linux']
      resources:
        limits:
          cpus: '0.33'
          memory: 20M
        reservations:
          cpus: '0.05'
          memory: 10M
    configs:
      - source: eg_gateway_config
        target: /var/lib/eg/gateway.config.yml
      - source: eg_system_config
        target: /var/lib/eg/system.config.yml
      - source: eg_applications_models
        target: /var/lib/eg/models/applications.json
      - source: eg_credentials_models
        target: /var/lib/eg/models/credentials.json
      - source: eg_users_models
        target: /var/lib/eg/models/users.json
```

Unfortunately EG seems to have problems with taking over my config files, or I get it wrong, but usually it works like this.

```bash
users.json file not found in / - copying now...
users.json file not found in / - copying now...
users.json file not found in / - copying now...
cp: can't create '/var/lib/eg/models/users.json': File exists
cp: can't create '/var/lib/eg/models/users.json': File exists
cp: can't create '/var/lib/eg/models/users.json': File exists
users.json file not found in / - copying now...
cp: can't create '/var/lib/eg/models/users.json': File exists
users.json file not found in / - copying now...
cp: can't create '/var/lib/eg/models/users.json': File exists
```
I have now read various statements about the config path, and also the possible environment variable... but I always get the same error!
