### ISSUE TITLE
How can I set proxyTimeout? Exactly where, need to put?

### ISSUE THREAD

**Issue by sjahongir** [ExpressGateway/express-gateway#871]

**Comment by XVincentX** [comment]
In the proxy policy options: https://www.express-gateway.io/docs/policies/proxy/#options-reference

**Comment by sjahongir** [comment]
Like this?

```
http:
  port: 9091

apiEndpoints:
  api:
    path: '*'

serviceEndpoints:
  example: # will be referenced in proxy policy
    url: 'http://example.com'

pipelines:
  example-pipeline:
    apiEndpoints:   # process all request matching "api" apiEndpoint
      - api
    policies:
      proxy: # name of the policy
        -   # list of actions
          proxyTimeout: 600000
          condition:
            name: pathExact
            path: /admin
          action:
            serviceEndpoint: example # reference to serviceEndpoints Section
```

**Comment by XVincentX** [comment]
You got it!

**Comment by sjahongir** [comment]
Thanks!

**Comment by sjahongir** [comment]
I set timeout (10 minutes) as following:

**Comment by sjahongir** [comment]
I set timeout 60000 ms
Here part of my config:
```
https:
  port: 8080
  tls:
    "default":
       key: 'config/keys/certs/key.pem'
       cert: 'config/keys/certs/cert.pem'
       ca: []
# admin:
#   port: 9876
#   hostname: localhost
apiEndpoints:
  qpServiceApi:
    host: '*'
    paths: ['/qp/*', '/qp']
  serviceEndpoints:
  qpService:
    url: 'http://127.0.0.1:4118'
  policies:
  # - basic-auth
  # - cors
  # - expression
  # - key-auth
  # - log
  # - oauth2
  - rewrite
  - proxy
  # - rate-limit
  - rs-security
pipelines:
    - name: qpServicePipeline
      apiEndpoints:
        - qpServiceApi
      policies:
        - rewrite:
          -
            condition:
              name: pathmatch
              match: /qp
            action:
              rewrite: /
          -
            condition:
              name: pathmatch
              match: /qp/:route*
            action:
              rewrite: /:route
        - proxy:
            - 
              proxyTimeout: 600000
              action:
                serviceEndpoint: qpService
                changeOrigin: true
```
But not working!

> Getting timeout exception after 2 minutes
