### ISSUE TITLE
proxyTimeout not working 

### ISSUE THREAD

**Issue by sjahongir** [ExpressGateway/express-gateway#872]
I set timeout 60000 ms
Here my config:
```
https:
  port: 8080
  tls:
    "default":
       key: 'config/keys/certs/key.pem'
       cert: 'config/keys/certs/cert.pem'
       ca: []
# admin:
#   port: 9876
#   hostname: localhost
apiEndpoints:
  qpServiceApi:
    host: '*'
    paths: ['/qp/*', '/qp']
  serviceEndpoints:
  qpService:
    url: 'http://127.0.0.1:4118'
  policies:
  # - basic-auth
  # - cors
  # - expression
  # - key-auth
  # - log
  # - oauth2
  - rewrite
  - proxy
  # - rate-limit
  - rs-security
pipelines:
    - name: qpServicePipeline
      apiEndpoints:
        - qpServiceApi
      policies:
        - rewrite:
          -
            condition:
              name: pathmatch
              match: /qp
            action:
              rewrite: /
          -
            condition:
              name: pathmatch
              match: /qp/:route*
            action:
              rewrite: /:route
        - proxy:
            - 
              proxyTimeout: 600000
              action:
                serviceEndpoint: qpService
                changeOrigin: true
```
But not working!

> Getting timeout exception after 2 minutes

**Comment by sjahongir** [comment]
@XVincentX can you help me?

**Comment by XVincentX** [comment]
I'll see if I can jump on this later today.

**Comment by sjahongir** [comment]
@XVincentX I found solution.

```
- proxy:
      - action:
            serviceEndpoint: qpService
            changeOrigin: true
            timeout: 600000
```
I used **timeout** option instead of **proxyTimeout**
