### ISSUE TITLE
express-gateway disable TLSv1.0

### ISSUE THREAD

**Issue by Shamith005** [ExpressGateway/express-gateway#873]
Any suggestion to disable TLSv1.0 from HTTPS responses of express-gateway? I'm unable to configure "gateway.config.yml" for this.

**Comment by XVincentX** [comment]
Hey,

I believe you should be able to do that by using

```yaml
https:
  options:
    secureOptions: 67108864
```

Let me know if that works and feel free to reopen if it does not @Shamith005
