### ISSUE TITLE
cors issue to get data in the frontend

### ISSUE THREAD

**Issue by sagar233426** [ExpressGateway/express-gateway#902]
I am integrating angular as frontend but having the below cors related issue while using it for EG:admin API i am getting the desired json output in response preview i have tried adding 'Access-Control-Allow-Origin' in allowedHeaders.  

I am getting below mentioned error in console:
Access to XMLHttpRequest at 'http://localhost:9876/users' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Below is my gateway.config.yml

http:
  port: ${EG_HTTP_PORT:-8080}

apiEndpoints:
  api:
    host: localhost
admin: 
  port: 9876
  hostname: localhost 
serviceEndpoints:
  backend:
    url: 'http://localhost:9876' 
policies:
  - cors
  - proxy
  - key-auth
pipelines:
  adminAPI:
    apiEndpoints:
      - api
    policies:
      - cors:
          - action:
              origin: "*"
              methods: 'HEAD,PUT,PATCH,POST,DELETE'
              allowedHeaders: "Origin, X-Requested-With, Content-Type, Accept"
              preflightContinue: true
      - proxy:
          - action:
              serviceEndpoint: backend

**Comment by XVincentX** [comment]
The behavior is indeed correct. Since you're exposing the admin API through the gateway what you want to do is to reach the admin api using the gateway url, not the admin API's raw one.

**Comment by sagar233426** [comment]
Can you send an example of it cause I'm little bit confuse.

Thanks

**Comment by NomadXD** [comment]
@XVincentX  I am facing the same issue and there is no solution. I was trying for like 10 hours but couldn't find a proper solution.

```
policies:
      - cors:
        - action:
            origin: '*'
            credentials: true
            methods: ['GET','POST','PUT','DELETE']
            allowedHeaders: ['Content-type','Authorization','Origin','Access-Control-Allow-Origin','Origin', 'Accept', 'X-Requested-With', 'Content-Type', 'Access-Control-Request-Method', 'Access-Control-Request-Headers','Authorization', 'Access-Control-Allow-Origin','X-TEST']
            exposedHeaders : ['Content-type','Authorization','Origin','Access-Control-Allow-Origin','Origin', 'Accept', 'X-Requested-With', 'Content-Type', 'Access-Control-Request-Method', 'Access-Control-Request-Headers','Authorization', 'Access-Control-Allow-Origin','X-TEST']
            preflightContinue: true
      - jwt:
        - action:
            secretOrPublicKey: 'secret'
            checkCredentialExistence: false
      - request-transformer:
        - action:
            body:
              add:
                user: req.user
      - proxy:
        - action:
            serviceEndpoint: noAuthService
```
When I use the following configuration, I get the following error.

```
Access to XMLHttpRequest at 'http://localhost:8080/api/user/31a19f8a-c76d-4051-a944-dad1b676c550' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

I think it's a more generic issue. Not something related to that admin API thing. Any ideas how to fix?? Thanks in advance
