### ISSUE TITLE
Bug: Proxy policy "hostRewrite" option fails with exception: The "url" argument must be of type string. Received type object

### ISSUE THREAD

**Issue by Andycharalambous** [ExpressGateway/express-gateway#904]
When I try to use the following setup, i get an error in the logs:

```
policies:
          -
            proxy:
              -
                action:
                  serviceEndpoint: my-endpoint
                  hostRewrite: "host.mydomain.com" <-- This causes the error
                  xfwd: true
                  protocolRewrite: "https"
```
```
url.js:154
    throw new ERR_INVALID_ARG_TYPE('url', 'string', url);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type object
    at Url.parse (url.js:154:11)
    at Object.urlParse [as parse] (url.js:148:13)
    at Array.setRedirectHostRewrite (/usr/local/share/.config/yarn/global/node_modules/http-proxy/lib/http-proxy/passes/web-outgoing.js:54:24)
    at ClientRequest.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:175:22)
```

the target property of the options object being passed through to http-proxy in the proxy policy code is an object rather than a string.

Line 54 of web-outgoing.js (as seen in the stack trace above) is:

`var target = url.parse(options.target);`

The actual url is at options.target.href. 

As can be seen in the proxy policy code:

```
logger.debug(`proxying to ${target.href}, ${req.method} ${req.url}`);
proxy.web(req, res, { target, headers, buffer: req.egContext.requestStream });
```

this should probably be:

```
logger.debug(`proxying to ${target.href}, ${req.method} ${req.url}`);
proxy.web(req, res, { target: target.href, headers, buffer: req.egContext.requestStream });
```
