### ISSUE TITLE
Property consumer is undefined in exContext

### ISSUE THREAD

**Issue by mike-pun** [ExpressGateway/express-gateway#908]
The following policy generates an error "Cannot read property 'id' of undefined. This came from an example in the documentation. It looks like the object **consumer** is undefined in the exContext. I tried using **consumer** in an expression with essentially the same result. Went to the documentation and used example code to verify.

```
      - headers:
          - action:
              headersPrefix: 'eg-'
              forwardHeaders:
                id: 'consumer.id'
                consumer-name: 'consumer.name'
                consumer-type: 'consumer.type'
                requestID: 'requestID'
                scopes: 'consumer.token.scopes'
```

Running eg v1.16.3
