### ISSUE TITLE
Bug: condition under builtin policies are parsed as actions as well

### ISSUE THREAD

**Issue by ailisp** [ExpressGateway/express-gateway#912]
Steps to reproduce, change official example in https://www.express-gateway.io/docs/configuration/, add a condition section under jwt:
```yaml
      - jwt: 
        - action:
            secretOrPublicKey: "some-key"
            checkCredentialExistence: false
        - condition:
            name: expression
            expression: "req.get('some-custom-header') == 'some-custom-value'"
```
In this case expressgateway will complain: 
```
2019-05-06T17:06:52.280Z [EG:policy] error: Policy jwt params validation failed: data should have required property '.secretOrPublicKey', data should have required property '.secretOrPublicKeyFile', data should match exactly one schema in oneOf
```
If remove condition section it works fine.

In further if in `lib/policies/jwt/jwt.js` I add a  `console.log(params)`:
![image](https://user-images.githubusercontent.com/13259400/57244841-52ef3080-7007-11e9-8c1c-1c5c6c4127b0.png)
And in `lib/policies/jwt/index.js` comment out the `oneOf` checking:
![image](https://user-images.githubusercontent.com/13259400/57244885-6c907800-7007-11e9-8f0d-d383afe200dd.png)

Now rerun `npm start`, params got output twice:
```json
{
  secretOrPublicKey: 'some-key',
  checkCredentialExistence: false,
  getCommonAuthCallback: [Function],
  jwtExtractor: 'authBearer'
}
{
  getCommonAuthCallback: [Function],
  jwtExtractor: 'authBearer',
  checkCredentialExistence: true
}
```
And when without `condition` section it only output once. So I think the condition section got parsed as if it's an action section, too. I also tried `console.log(params)` in proxy policy and in key-auth policy, they all have the same issue.

**Comment by ailisp** [comment]
Sorry I think I found what was wrong, not a bug, it's i typo the map as an array:
```
      - jwt: 
        - action:
            secretOrPublicKey: "some-key"
            checkCredentialExistence: false
        - condition:
            name: expression
            expression: "req.get('some-custom-header') == 'some-custom-value'"
```
should be no `-` before `condition` and it works
