### ISSUE TITLE
Multiple services endpoints implementation

### ISSUE THREAD

**Issue by v2karora** [ExpressGateway/express-gateway#917]
Hi All,

What is the procedure to implement a scenario where multiple services are involved in a project. I can set a single proxy in a given pipeline but can not multiple. Please look into below gateway.config.yml - I can use usersService but how can I use others 2 services i.e. productsService and transactionsService? If my question is not clear please let me know. TIA

```yml
http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  #see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints
  gatewayAPI:
    host: 'vue.gateway.sg'
    paths:
      - '/users'
      - '/products'
      - '/transactions'
serviceEndpoints:
  #see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/serviceEndpoints
  usersService:
    url: 'http://localhost:8059'
  productsService:
    url: 'http://localhost:8060'
  transactionsService:
    url: 'http://localhost:8061'
policies:
  - expression
  - key-auth
  - proxy
pipelines:
  - name: users
    apiEndpoints:
      - gatewayAPI
    policies:
      - proxy:
        - action:
             serviceEndpoint: usersService
        #- action:
           #serviceEndpoint: productsService
        #- action:
           #serviceEndpoint: transactionsService
  #see: https://www.express-gateway.io/docs/configuration/gateway.config.yml/pipelines
```
