### ISSUE TITLE
Getting Started guide gives 404

### ISSUE THREAD

**Issue by jayhjha** [ExpressGateway/express-gateway#928]
Just started looking at express-gateway and was following the [Getting Started guide](https://www.express-gateway.io/getting-started/).
Didn't make any changes to `gateway.config.yml`, but when I try `curl http://localhost:8080/ip`, I get a `404 Page not found` error.

Here's the config file for reference:
```
http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
```
