### ISSUE TITLE
response transformer policy not working

### ISSUE THREAD

**Issue by jayhjha** [ExpressGateway/express-gateway#929]
I am trying to use response transformer policy to add a new key to the response, but it's not working. Here's the snippet from my config file:

```
- response-transformer:
        - 
          action:
            body:
              add:
                test: 'testing'
```

Any idea why?
