### ISSUE TITLE
[Question] OAuth 2 Introspection in 2 different pipelines

### ISSUE THREAD

**Issue by tagkiller** [ExpressGateway/express-gateway#941]
Hi all,

I have an issue using OAuth 2 Introspection accross multiple pipelines.
So my first question is it even possible to use it that way ?
I configured 2 `apiEndpoints` and wants each one to use a specific `oauth2-introspect` endpoint. The thing it's whether I enter the first or the second pipeline, it's always the last `oauth2-introspect` endpoint configured that's hitting.

```
http:
  port: 8888
admin:
  port: 9876
  host: 0.0.0.0
apiEndpoints:
  managementAPI:
    host: localhost
    paths: '/a/management/*'
  usersAPI:
    host: localhost
    paths: '/a/*'
serviceEndpoints:
  ProvisioningService:
    url: 'http://provisioning.service:8080'
policies:
  - proxy
  - rewrite
  - request-transformer
  - oauth2-introspect
pipelines:
  usersservice:
    apiEndpoints:
      - usersAPI
    policies:
      - oauth2-introspect:
        - action:
            endpoint: 'http://security.service:8080/introspect'
            authorization_value: 'Bearer someToken'
            ttl: 60
      - request-transformer:
        - action:
            headers:
              add:
                x-auth-principal: "req.user.sub"
                x-auth-scope: "req.user.scope"
      - proxy:
          - action:
              serviceEndpoint: ProvisioningService
              changeOrigin: true
              stripPath: true
              proxyTimeout: 1000
  managementservice:
    apiEndpoints:
      - managementAPI
    policies:
      - oauth2-introspect:
        - action:
            endpoint: 'https://management.service:8080/introspect'
            ttl: 60
      - request-transformer:
        - action:
            headers:
              add:
                x-auth-principal: "req.user.sub"
                x-auth-scope: "req.user.scope"
      - rewrite:
        - condition:
            name: pathmatch
            match: /a/management/:code # Express Path
          action:
            rewrite: /a/:code
      - proxy:
          - action:
              serviceEndpoint: ProvisioningService
              changeOrigin: true
              stripPath: true
              proxyTimeout: 1000
``` 

Could you please help me with this matter ? Am I doing something wrong or is it a bug ?

Thanks in advance.

Best regards,

**Comment by XVincentX** [comment]
I've just tried this configuration and I've correctly hit the two proposed endpoints. Can you provide a screenshot or something to investigate?

Feel free to reopen

**Comment by tagkiller** [comment]
Hi @XVincentX ,

I added some logging to the pipelines with this :

```
- log:
        - action: 
            message: "usersservice - ${req.method} ${req.ip} ${req.body} ${req.originalUrl}"
...
- log:
        - action:
            message: "managementservice - ${req.method} ${req.ip} ${req.body} ${req.originalUrl}"
```

Here is some additionnal logs :

```
2019-09-04T14:25:25.510Z [EG:log-policy] info: usersservice - POST ::1 undefined /a/device/stb123456/esn
https://management.service:8080/introspect
2019-09-04T14:26:58.813Z [EG:log-policy] info: managementservice - POST ::1 undefined /a/management/device/stb123456/esn
https://management.service:8080/introspect
```

I also added a `console.log(options.endpoint)` in the `token-introspector.js` and as you can see above it logs two times the same oAuth2 Introspection token.
I think it's a bug.

Could you please help me with this matter ?

Best regards,

**Comment by XVincentX** [comment]
Are you using the exact configuration file you posted above?

**Comment by tagkiller** [comment]
Yes, I do have this exact configuration, except that the endpoints are real
and working on my side.

**Comment by XVincentX** [comment]
Yeah I think the real problem here is that your pipeline order is incorrect. By installing the less specific one first instead of the most specific, the first one is catching all the requests; the `/a/management/*` pipeline is never being hit, since all the request are catch by the more generic one.

You can solve this by reverting the pipeline order.

**Comment by tagkiller** [comment]
I don't think it's related.
If you look closely at the logs you can see that I hit two different endpoints :
```
2019-09-04T14:25:25.510Z [EG:log-policy] info: usersservice - POST ::1 undefined /a/device/stb123456/esn
https://management.service:8080/introspect
2019-09-04T14:26:58.813Z [EG:log-policy] info: managementservice - POST ::1 undefined /a/management/device/stb123456/esn
https://management.service:8080/introspect
```

Just in case I tried also with two different path like : 
```
apiEndpoints:
  managementAPI:
    host: localhost
    paths: '/a/management/*'
  usersAPI:
    host: localhost
    paths: '/a/users/*'
```

It was still not working. Also quoting the official documentation of Express-gateway :
> The order of the API endpoints specified matters. It is possible to specifiy overlapping patterns through wildcards. More specific patterns should be specified first for prioritized evaluation before more general matching.

So, I really think it's a bug, look at the OAuth2 Introspection endpoint being logged.
For some reason the options used in the plugin seems to only keep the latest pipeline configuration.
I can look thoroughly in the plugin later today, to pinpoint where the issue is.

Did you try the configuration I provided ?

Thanks a lot for your help, it's really appreciated :-)
