### ISSUE TITLE
REDIS DB Password not working [question]

### ISSUE THREAD

**Issue by ffalor** [ExpressGateway/express-gateway#951]
I added a password to my redis db. I am able to connect manually with a password, but when i try to run eg users create i get an error saying the db requires authentication. What is wrong with my system.conf file?

System.conf

```
db:
  redis:
    host: express_db
    port: 6379
    namespace: EG
    options:
      password: password
```
Also tried 
```
    options:
      - password: password
```
And
```
    namespace: EG
    password: password
```

None of the above works

**Comment by ffalor** [comment]
No one know how to do this? The docs obviously don't explain it, and none of the above worked for me.

**Comment by tabishz** [comment]
I have the following working for me:
```
db:
  redis:
    host: '127.0.0.1'
    port: 6379
    namespace: EG
    password: 'secretpassword'
    connectionName: 'exp-gateway'
```
