### ISSUE TITLE
proxy stripPath incorrectly URL decodes the path

### ISSUE THREAD

**Issue by judev** [ExpressGateway/express-gateway#963]
When using `stripPath` on a proxy policy, the path passed on to the proxy is URL decoded. This can cause the incorrect URL to be requested from the proxy. An example of when maintaining the URL encoding of path components is important is in the Gitlab API where requesting a project file takes the form `https://gitlab.example.com/api/v4/projects/backend-services%2Fauth` (projects are namespaced with a URL-encoded forward slash).

This seems to be caused by using `req.params[0]` in `stripPathFn` in `proxy.js`. It should instead strip the matched path from the beginning of `req.url` to ensure the encoding isn't messed with by express.

Example `gateway.config.yml` follows, run with `LOG_LEVEL=debug` and note the difference in the logged message when requesting `http://localhost:8080/test-path-encoding/path%2Fto%2Fresource` vs `http://localhost:8080/test-strip-path-encoding/path%2Fto%2Fresource`.
To avoid confusion please ignore the httpbin response given by this example, as httpbin has a similar issue in that it always decodes the `url` in the `/anything` response.

```
http:
  port: 8080
apiEndpoints:
  test_path_nostrip:
    host: localhost
    paths: '/test-path-encoding/*'
  test_path_strip:
    host: localhost
    paths: '/test-strip-path-encoding/*'
serviceEndpoints:
  httpbin:
    url: 'http://httpbin.org/anything'
policies:
  - proxy
pipelines:
  nostripPath:
    apiEndpoints:
      - test_path_nostrip
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
  stripPath:
    apiEndpoints:
      - test_path_strip
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              stripPath: true
```
