### ISSUE TITLE
distinguish the services with same path

### ISSUE THREAD

**Issue by ramiz4** [ExpressGateway/express-gateway#964]
```
const express = require('express');
const svc1 = express();
svc1.get('/healthz', (req, res, next) => {
    res.send({ name: 'svc1', status: 'healthy' });
    next();
}).listen(process.env.PORT || 1337);

const svc2 = express();
svc2.get('/healthz', (req, res, next) => {
    res.send({ name: 'svc2', status: 'healthy' });
    next();
}).listen(process.env.PORT2 || 1338);
```

How can I distinguish the services in the express-gateway if the paths are the same?

```
http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  svc1API:
    host: 'localhost'
    paths:
      - '/health-check'
  svc2API:
    host: 'localhost'
    paths:
      - '/health-check'
serviceEndpoints:
  svc1Service:
    url: 'http://localhost:1337'
  svc2Service:
    url: 'http://localhost:1338'
policies:
  - proxy
pipelines:
  - name: svc1
    apiEndpoints:
      - svc1API
    policies:
      - proxy:
        - action:
            serviceEndpoint: svc1Service
  - name: svc2
    apiEndpoints:
      - svc2API
    policies:
      - proxy:
        - action:
            serviceEndpoint: svc2Service
```
