### ISSUE TITLE
Bad gateway

### ISSUE THREAD

**Issue by kKen94** [ExpressGateway/express-gateway#973]
I create Express Gateway with option "Getting Started with Express Gateway", and this is gateway.config.yml

```
http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true

```

I simply change `url: 'https://httpbin.org'` to `url: 'http://localhost:3001'` and i have or Bad Gateway or other error.

If I call localhost:3001 directly i have the response of my service
