### ISSUE TITLE
[Question] Proxy changeOrigin not doing anything

### ISSUE THREAD

**Issue by jclaessens97** [ExpressGateway/express-gateway#985]
How I understand is the changeProxy option in the proxy policy meant to change he origin header to the gateway's origing and not from the e.g. browser's origin right?

If that's not what it's meant to do, please correct me and explain what it is meant to do 😉

If that IS what it's meant to do, it doesn't seem to work:

```     
- proxy:
          action:
                serviceEndpoint: coreService
                changeOrigin: true
```

True or false, the origin I receive in my backend is always the origin of the browser and not of my gateway. I only want to allow the CORS from the gateway, not from the frontend if that's possible.

Thanks!
